"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
[ÓÇ∞](fg:blue bg:surface0)\
$directory\
[ÓÇ∞](fg:surface0 bg:yellow)\
$git_branch\
$git_status\
[ÓÇ∞](fg:yellow bg:green)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[ÓÇ∞](fg:green bg:cyan)\
$conda\
[ÓÇ∞](fg:cyan bg:magenta)\
$time\
[ÓÇ∞ ](fg:magenta)\
$cmd_duration\
$character"""

palette = 'tokyo_night'

[line_break]
disabled = true

[username]
show_always = true
style_user = "bg:blue fg:black"
style_root = "bg:blue fg:black"
format = '[ $user ]($style)'

[directory]
style = "bg:surface0 fg:blue"
format = "[ $path ]($style)"
truncation_length = 3

[git_branch]
symbol = "Ôêò"
style = "bg:yellow"
format = '[[ $symbol $branch ](fg:black bg:yellow)]($style)'

[git_status]
style = "bg:yellow"
format = '[[($all_status$ahead_behind )](fg:black bg:yellow)]($style)'

[golang]
symbol = "üêπ"
style = "bg:green"
format = '[[ $symbol ($version) ](fg:black bg:green)]($style)'

[nodejs]
symbol = "Óúò"
style = "bg:green"
format = '[[ $symbol ($version) ](fg:black bg:green)]($style)'

[rust]
symbol = "Óû®"
style = "bg:green"
format = '[[ $symbol ($version) ](fg:black bg:green)]($style)'

[c]
symbol = "Óòû"
style = "bg:green"
format = '[[ $symbol ($version) ](fg:black bg:green)]($style)'

[python]
symbol = "ÓòÜ"
style = "bg:green"
format = '[[ $symbol ($version) ](fg:black bg:green)]($style)'

[php]
symbol = "Óòà"
style = "bg:green"
format = '[[ $symbol ($version) ](fg:black bg:green)]($style)'

[java]
symbol = "Óâñ"
style = "bg:green"
format = '[[ $symbol ($version) ](fg:black bg:green)]($style)'

# --------------------------------------------------

[conda]
symbol = " ÔÑå "
style = "fg:black bg:cyan"
format = '[$symbol$environment ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:magenta"
format = '[[ Ôê∫ $time ](fg:black bg:magenta)]($style)'

[character]
disabled = false
success_symbol = ""
error_symbol = ""

[cmd_duration]
style = "fg:yellow"
format = "Ó´¥ $duration "

[palettes.tokyo_night]
black = "#15161e"
foreground = "#a9b1d6"
surface0 = "#292e42"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
magenta = "#bb9af7"
orange = "#ff9e64"
red = "#f7768e"
yellow = "#e0af68"
